openapi: 3.0.0
info:
  title: "Project Tracker Web API"
  version: "1.0.0"
  contact:
    name: Eduardo Jaime
    email: ejaime@amazingdevs.ca
    url: https://amazingdevs.ca
servers:
  - url: http://localhost:3000/api
  - url: https://eastus-projecttracker.ca/api
  - url: https://canada-projecttracker.ca/api
tags:
  - name: Georgian College
    description: This is our college name
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
paths:
  /projects:
    get:
      tags:
        - "Georgian College"
      security:
        - basicAuth: []
      description: Returns a list of projects
      parameters:
        - name: status
          in: query
          required: false
          description: Status of the projects
          schema:
            type: string
            enum:
              - TO DO
              - IN PROGRESS
              - DONE
        - name: course
          in: query
          required: false
          description: Course that the project belongs to
          schema:
            type: string
      responses:
        "200":
          description: Unfiltered list of projects