openapi: 3.0.0
info:
  title: "Project Tracker API"
  version: "1.0.0"
  contact:
    name: Eduardo Jaime
    email: ejaime@amazingdevs.ca
    url: https://amazingdevs.ca/
servers:
  - url: http://localhost:3000/api
  - url: https://amazingdevs.ca/api
tags:
  - name: Georgian College
    description: Our college name
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
paths:
  /projects:
    get:
      tags:
        - Georgian College
      summary: Get all projects
      security:
        - basicAuth: []
      parameters:
        - in: query
          name: status
          schema:
            type: string
            enum:
              - TO DO
              - IN PROGRESS
              - DONE
          description: Filter projects by status
          required: false
        - in: query
          name: course
          schema:
            type: string
          description: Filter projects by course
          required: false
      responses:
        '200':
          description: A list of projects